### ISSUE TITLE
Maven Repository is Private

### ISSUE THREAD

**Issue by inception-cto** [DexCare/DexCareSDK-Android#1]
We are not able to build using the following configuration

```gradle
repositories {
        // required for rxpermissions (DexCare SDK dependency)
        maven { url "https://jitpack.io" }

        // required for tokbox (DexCare SDK dependency)
        maven { url 'https://tokbox.bintray.com/maven' }
	maven {
		url "https://maven.pkg.github.com/DexCare/DexCareSDK-Android/"
	}
}
```

It appears that the `maven` repository is private and is not accessible publicly.

**Comment by jamesthacker** [comment]
I believe this was resolved the same day the issue was opened.  I am currently seeing the maven repository as public and able to download it without credentials.

**Comment by jamesthacker** [comment]
@melek-inception As it turns out, GitHub's maven requires authentication even for public packages.  See this comment: https://github.community/t/how-to-allow-unauthorised-read-access-to-github-packages-maven-repository/115517/3

The credentials block is apparently still necessary.  I'll update the documentation for this.
